spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true
    default-schema: public

  jpa:
    properties:
      hibernate:
        default_schema: public



